# Generated by Django 2.2 on 2020-02-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('measured_type', models.CharField(choices=[('FEET', 'FEET'), ('INCHES', 'INCHES')], max_length=100)),
                ('area_total', models.CharField(max_length=150)),
                ('icon', models.ImageField(upload_to='environment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
