# Generated by Django 2.2 on 2020-02-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase_two', '0002_apto_model_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='utility',
            field=models.CharField(default='0', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apto_model',
            name='identifier',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='apto_model',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
