# Generated by Django 2.2 on 2020-02-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase_two', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_builings', models.CharField(max_length=100)),
                ('number_floors', models.CharField(max_length=100)),
            ],
        ),
    ]
