# Generated by Django 2.2 on 2020-02-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase_one', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='material',
            name='subcategory_two',
        ),
        migrations.RemoveField(
            model_name='material',
            name='type_measure',
        ),
        migrations.AddField(
            model_name='material',
            name='area_total',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='environment',
            field=models.CharField(choices=[('KITCHEN', 'KITCHEN'), ('GARDEN', 'GARDEN'), ('LIVING_ROOM', 'LIVING ROOM'), ('DINNING_ROOM', 'DINNING ROOM')], default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='icon',
            field=models.ImageField(default='none', upload_to='material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='measured_type',
            field=models.CharField(choices=[('FEET', 'FEET'), ('INCHES', 'INCHES')], default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='price',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='reference',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
