# Generated by Django 2.2 on 2020-02-20 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phase_one', '0005_auto_20200220_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='material',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='phase_one.Material'),
            preserve_default=False,
        ),
    ]
